name: 同步Gitee subtree上游模块
on:
  schedule:
    - cron: '0 3 * * *' # UTC03:00 = 北京时间11:00 每日执行
  workflow_dispatch: # 支持网页手动触发调试

# 授予代码写入权限，解决git push 403
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出完整main分支代码
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0 # subtree必须拉全量git历史

      - name: 配置Git提交机器人身份
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: 拉取Gitee最新代码到dd子目录
        id: sync_step
        run: |
          GITEE_URL="https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/lr-avionics/test.git"
          # 正确subtree语法，绑定dd子目录
          if git subtree pull --prefix=dd "$GITEE_URL" main --squash -m "sync: 同步Gitee模块最新代码"; then
            echo "has_update=true" >> $GITHUB_OUTPUT
          else
            echo "Gitee无新更新，跳过推送"
            echo "has_update=false" >> $GITHUB_OUTPUT
          fi

      - name: 仅存在更新时推送到GitHub main分支
        if: steps.sync_step.outputs.has_update == 'true'
        run: git push --force origin main
